export const planetSymbols: { [key: string]: { [key: string]: string } } = {
  'ro': {
    'Soare': '☉',
    'Luna': '☽',
    'Mercur': '☿',
    'Venus': '♀',
    'Marte': '♂',
    'Jupiter': '♃',
    'Saturn': '♄',
    'Uranus': '♅',
    'Neptun': '♆',
    'Pluto': '♇',
    'Ascendent': '↑',
    'Descendent': '↓',
    'Lilith': '⚸',
    'Chiron': '⚷',
    'Nodul Nord': '☊',
    'Nodul Sud': '☋',
    'Mijlocul Cerului': 'MC',
    'Fundul Cerului': 'IC'
  },
  'en': {
    'Sun': '☉',
    'Moon': '☽',
    'Mercury': '☿',
    'Venus': '♀',
    'Mars': '♂',
    'Jupiter': '♃',
    'Saturn': '♄',
    'Uranus': '♅',
    'Neptune': '♆',
    'Pluto': '♇',
    'Ascendant': '↑',
    'Descendant': '↓',
    'Lilith': '⚸',
    'Kiron': '⚷',
    'North Node': '☊',
    'South Node': '☋',
    'Medium Coeli': 'MC',
    'Imum Coeli': 'IC'
  },
};

export const zodiacSymbols: { [key: string]: { [key: string]: string } } = {
  "ro": {
    'Berbec': '♈',
    'Taur': '♉',
    'Gemeni': '♊',
    'Rac': '♋',
    'Leu': '♌',
    'Fecioara': '♍',
    'Balanta': '♎',
    'Scorpion': '♏',
    'Sagetator': '♐',
    'Capricorn': '♑',
    'Varsator': '♒',
    'Pesti': '♓',
  },
  "en": {
    'Aries': '♈',
    'Taurus': '♉',
    'Gemini': '♊',
    'Cancer': '♋',
    'Leo': '♌',
    'Virgo': '♍',
    'Libra': '♎',
    'Scorpio': '♏',
    'Sagittarius': '♐',
    'Capricorn': '♑',
    'Aquarius': '♒',
    'Pisces': '♓',
  },
};

export const zodiacOrder: string[] = [
  'Aries',
  'Taurus',
  'Gemini',
  'Cancer',
  'Leo',
  'Virgo',
  'Libra',
  'Scorpio',
  'Sagittarius',
  'Capricorn',
  'Aquarius',
  'Pisces'
];

export const planetOrder: string[] = [
  'Sun',
  'Moon',
  'Mercury',
  'Venus',
  'Mars',
  'Jupiter',
  'Saturn',
  'Uranus',
  'Neptune',
  'Pluto',
  'Ascendant',
  'Lilith',
  'Kiron',
  'North Node',
  'South Node'
];
